//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatzesMusicShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public int CdID { get; set; }
        public string Text { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual CDs CDs { get; set; }
    }
}
